# Generated by Django 5.2.9 on 2026-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='СуммаБюджета')),
            ],
            options={
                'db_table': '[Производство].[Бюджет]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dolzhnosti',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Должность', max_length=100)),
            ],
            options={
                'db_table': '[Производство].[Должности]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdiniziIzmerenia',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование', max_length=50)),
            ],
            options={
                'db_table': '[Производство].[ЕдиницыИзмерения]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GotovayaProdukcia',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование', max_length=150)),
                ('quantity', models.FloatField(db_column='Количество')),
                ('amount', models.FloatField(db_column='Сумма')),
            ],
            options={
                'db_table': '[Производство].[ГотоваяПродукция]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredienty',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Количество')),
            ],
            options={
                'db_table': '[Производство].[Ингредиенты]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdazhaProdukcii',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Количество')),
                ('amount', models.FloatField(db_column='Сумма')),
                ('date', models.DateTimeField(db_column='Дата')),
            ],
            options={
                'db_table': '[Производство].[ПродажаПродукции]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProizvodstvoProdukcii',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Количество')),
                ('date', models.DateTimeField(db_column='Дата')),
            ],
            options={
                'db_table': '[Производство].[ПроизводствоПродукции]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('fio', models.CharField(db_column='ФИО', max_length=200)),
                ('salary', models.FloatField(db_column='ЗаработнаяПлата')),
                ('address', models.CharField(blank=True, db_column='Адрес', max_length=300, null=True)),
                ('phone', models.CharField(blank=True, db_column='Телефон', max_length=30, null=True)),
            ],
            options={
                'db_table': '[Производство].[Сотрудники]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Syrie',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование', max_length=150)),
                ('quantity', models.FloatField(db_column='Количество')),
                ('amount', models.FloatField(db_column='Сумма')),
            ],
            options={
                'db_table': '[Производство].[Сырье]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZakupkaSyrya',
            fields=[
                ('id', models.AutoField(db_column='ИД', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='Количество')),
                ('amount', models.FloatField(db_column='Сумма')),
                ('date', models.DateTimeField(db_column='Дата')),
            ],
            options={
                'db_table': '[Производство].[ЗакупкаСырья]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Сумма', verbose_name='Сумма кредита')),
                ('is_paid', models.BooleanField(db_column='Погашен', default=False, verbose_name='Кредит погашен')),
                ('date_taken', models.DateTimeField(auto_now_add=True, db_column='Дата_Получения', verbose_name='Дата получения')),
            ],
            options={
                'db_table': 'Кредиты',
            },
        ),
    ]
