# Generated by Django 5.2.9 on 2026-04-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZayavkiNaProizvodstvo',
            fields=[
                ('id', models.AutoField(db_column='Идентификатор_заявки', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Дата_создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Дата_последнего_обновления', verbose_name='Дата последнего обновления')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('На проверке наличия сырья', 'На проверке наличия сырья'), ('На процессе закупки сырья', 'На процессе закупки сырья'), ('На процессе производства', 'На процессе производства'), ('На процессе продажи', 'На процессе продажи'), ('Выполнена', 'Выполнена'), ('Ошибка', 'Ошибка')], db_column='Статус', default='Создана', max_length=50, verbose_name='Статус')),
                ('applicant_fio', models.CharField(db_column='ФИО_заявителя', max_length=200, verbose_name='ФИО заявителя')),
                ('quantity', models.FloatField(db_column='Количество', default=1.0, verbose_name='Количество')),
                ('rejection_reason', models.TextField(blank=True, db_column='Причина_отказа', null=True, verbose_name='Причина отказа')),
                ('id_produkcii', models.ForeignKey(db_column='ИД_готовой_продукции', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gotovayaprodukcia', verbose_name='Идентификатор готовой продукции')),
            ],
            options={
                'verbose_name': 'Заявка на производство',
                'verbose_name_plural': 'Заявки на производство',
                'db_table': 'Заявки_на_производство',
            },
        ),
    ]
